- name: Play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print play variable
      ansible.builtin.debug:
       msg: URL = {{ URL }}

- name: Play variables from the files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print play variables from the files
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play variables
  hosts: localhost
  tasks:
    - vars:
        URL: play.sample.com
    - name: Print play variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}