- name: Play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print play variable
      ansible.builtin.debug:
       msg: URL = {{ URL }}

- name: Play variables from the files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print play variables from the files
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play variables
  hosts: localhost
  tasks:
    - name: Print play variables
      vars:
        URL: play.sample.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play variables from inventory
  hosts: all
  tasks:
    - name: print play variable from inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: print out
      ansible.builtin.debug:
        msg: "{{ out }}"